[build]
  # Netlify build command madhech install ani permissions set kara
  command = "npm install && chmod +x ./node_modules/.bin/vite && npm run build"
  publish = "dist"

[[redirects]]
  # React Router sathi he garajiche aahe
  from = "/*"
  to = "/index.html"
  status = 200