[build]
  command = "npm install && chmod +x ./node_modules/.bin/vite && npm run build"
  publish = "dist"

# Redirect API calls to Render
[[redirects]]
  from = "/api/*"
  to = "https://dubaip2p.onrender.com/api/:splat"
  status = 200
  force = true

# Fix for React Router page refreshes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200