[build]
  command = "npm run build"
  publish = "dist"
  # base = "client"  <-- HI LINE KADHUN TAKA KIVA COMMENT KARA

[[redirects]]
  from = "/api/*"
  to = "https://dubaip2p.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200